# Pytorch fundamentals

In [29]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1


# Introduction of Tensors

## Creating Tensors

In [30]:
# scalar
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.shape)
# Get tensor back as Python Int
print(scalar.item())

tensor(7)
0
torch.Size([])
7


In [31]:
# vector
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [32]:
# Matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [33]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(tensor.ndim)
print(tensor.shape)

3
torch.Size([1, 3, 3])


## Random Tensors
Why random tensors?

Random tensors are important because the way many neural network learn is that 
they start with tensors full of random numbers and then adjust those random numbers
to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [34]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
print(random_tensor)
print(random_tensor.ndim)

tensor([[0.4628, 0.5805, 0.4244, 0.1642],
        [0.9269, 0.2459, 0.5343, 0.7356],
        [0.9092, 0.7615, 0.2417, 0.4296]])
2


In [35]:
# Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # Colour channel (R, G, B), Height, Weight
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and ones

In [36]:
# Create a tensor of full of zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [37]:
# Create a tensor of full of ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [38]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [39]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
# Creating tensors like
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes
**Note:** Tensor Datatypes is one of the big 3 errors you'll run into with Pytorch & Deep learning: 
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [41]:
# Float-32 tensor
flotat_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None, # What datatype is the tensor (e.g float32, float16)
                                device=None, # What device is your tensor on 
                                requires_grad=False) # Whether or not to track gradients with this tensors operations
print(flotat_32_tensor)
print(flotat_32_tensor.dtype)

tensor([3., 6., 9.])
torch.float32


In [42]:
float_16_tensor = flotat_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [43]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to do get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to do get device from a tensor, can use `tensor.device`

In [44]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5395, 0.9481, 0.4424, 0.4622],
        [0.1466, 0.8092, 0.9290, 0.3155],
        [0.6540, 0.6078, 0.3071, 0.1307]])

In [45]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5395, 0.9481, 0.4424, 0.4622],
        [0.1466, 0.8092, 0.9290, 0.3155],
        [0.6540, 0.6078, 0.3071, 0.1307]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


## Manipulation Tensors (tensor operations)
Tensor operations include:
1. Addition
2. Substraction
3. Multiplication (element-wise)
4. Division
5. Matrix-multiplication

In [46]:
# Create a tensor
tensor = torch.rand(3)
tensor + 10

tensor([10.7805, 10.3270, 10.8572])

In [47]:
# Multiply a tensor by 10
tensor * 10

tensor([7.8046, 3.2703, 8.5719])

## Matrix Multiplication
Two main ways of performing multiplication in neural networks and deep learning :
 1. Element wise multiplication
 2. Matrix multiplication

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimension.**

In [48]:
# Element wise multiplication
print(tensor, "*" ,tensor)
print(f"Equals: {tensor * tensor}")

tensor([0.7805, 0.3270, 0.8572]) * tensor([0.7805, 0.3270, 0.8572])
Equals: tensor([0.6091, 0.1070, 0.7348])


In [49]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(1.4508)

In [50]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 514 μs, sys: 790 μs, total: 1.3 ms
Wall time: 1.27 ms


tensor(1.4508)

## One of the most common errors in deep learning: shape errors

In [51]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensor using a **transpose**

In [52]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [53]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [54]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

## Find the min, max, mean, sum, etc (tensor aggregation)

In [61]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [57]:
# Find the min
torch.min(x)

tensor(0)

In [58]:
# Find the max 
torch.max(x)

tensor(90)

In [62]:
# Find the mean
torch.mean(x.type(torch.float32))

tensor(45.)

In [63]:
# Find the sum
torch.sum(x)

tensor(450)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping
* View
* Stacking - combine multiple tensors on top each other (vstack) or side by side (hstack)
* Squeeze - removes all `1`  dimension from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.

In [11]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [12]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [17]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [18]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [21]:
# Stack tensors on top of each others
x_stacked = torch.stack([x, x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5., 5.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8.],
        [9., 9., 9., 9., 9.]])

In [27]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous tensor: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous tensor: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [31]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueezed
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [32]:
# torch.permute - rearrange the dimensions of a target tensor in a specific order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shift axis 0->1, 1->2, 2->0 

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with NumPy

In [34]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [35]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [36]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

## PyTorch tensors & Numpy

In [37]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

## Reproducibility (trying to take random out of random)

In short how a neuron network learns:

`Start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again -> again -> again...`

In [39]:
import torch

# Create two random tensors
random_tensors_A = torch.rand(3, 4)
random_tensors_B = torch.rand(3, 4)

print(random_tensors_A)
print(random_tensors_B)
print(random_tensors_A == random_tensors_B)

tensor([[0.7819, 0.7621, 0.3400, 0.7671],
        [0.0295, 0.9398, 0.8295, 0.7657],
        [0.3780, 0.7790, 0.9241, 0.4269]])
tensor([[0.6616, 0.7697, 0.0142, 0.9866],
        [0.5410, 0.6821, 0.7475, 0.2942],
        [0.5033, 0.6507, 0.2424, 0.7847]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [40]:
# Let's set some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDDIA hardware + PyTorch working behind the scenes to make everything hunky

In [2]:
# Check for GPU acces via PyTorch
import torch
torch.cuda.is_available()

False

In [3]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "CPU"
device

'CPU'

## 3. Putting tensors (and models) on the GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [4]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)

## 4. Moving tensors back to the CPU   

In [ ]:
# If tensor is on GPU, can't transform it to numpy
tensor_on_gpu.numpy()

In [ ]:
# To fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu