# Pytorch fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1


# Introduction of Tensors

## Creating Tensors

In [11]:
# scalar
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.shape)
# Get tensor back as Python Int
print(scalar.item())

tensor(7)
0
torch.Size([])
7


In [10]:
# vector
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [12]:
# Matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [23]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(tensor.ndim)
print(tensor.shape)

3
torch.Size([1, 3, 3])


## Random Tensors
Why random tensors?

Random tensors are important because the way many neural network learn is that 
they start with tensors full of random numbers and then adjust those random numbers
to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [29]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
print(random_tensor)
print(random_tensor.ndim)

tensor([[0.1681, 0.1719, 0.2667, 0.0484],
        [0.7699, 0.8753, 0.8464, 0.4779],
        [0.5514, 0.1565, 0.9603, 0.9042]])
2


In [30]:
# Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # Colour channel (R, G, B), Height, Weight
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [3]:
# Create a tensor of full of zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])