# Pytorch fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1


# Introduction of Tensors

## Creating Tensors

In [11]:
# scalar
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.shape)
# Get tensor back as Python Int
print(scalar.item())

tensor(7)
0
torch.Size([])
7


In [10]:
# vector
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [12]:
# Matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [23]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(tensor.ndim)
print(tensor.shape)

3
torch.Size([1, 3, 3])


## Random Tensors
Why random tensors?

Random tensors are important because the way many neural network learn is that 
they start with tensors full of random numbers and then adjust those random numbers
to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [29]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
print(random_tensor)
print(random_tensor.ndim)

tensor([[0.1681, 0.1719, 0.2667, 0.0484],
        [0.7699, 0.8753, 0.8464, 0.4779],
        [0.5514, 0.1565, 0.9603, 0.9042]])
2


In [30]:
# Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # Colour channel (R, G, B), Height, Weight
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [3]:
# Create a tensor of full of zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
# Create a tensor of full of ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [5]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [12]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
# Creating tensors like
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes
**Note:** Tensor Datatypes is one of the big 3 errors you'll run into with Pytorch & Deep learning: 
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [4]:
# Float-32 tensor
flotat_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None, # What datatype is the tensor (e.g float32, float16)
                                device=None, # What device is your tensor on 
                                requires_grad=False) # Whether or not to track gradients with this tensors operations
print(flotat_32_tensor)
print(flotat_32_tensor.dtype)

tensor([3., 6., 9.])
torch.float32


In [5]:
float_16_tensor = flotat_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [3]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to do get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to do get device from a tensor, can use `tensor.device`

In [4]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0115, 0.7634, 0.6935, 0.2466],
        [0.1847, 0.7617, 0.5175, 0.5343],
        [0.5981, 0.1463, 0.4928, 0.5572]])

In [8]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0115, 0.7634, 0.6935, 0.2466],
        [0.1847, 0.7617, 0.5175, 0.5343],
        [0.5981, 0.1463, 0.4928, 0.5572]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


## Manipulation Tensors (tensor operations)
Tensor operations include:
1. Addition
2. Substraction
3. Multiplication (element-wise)
4. Division
5. Matrix-multiplication

In [10]:
# Create a tensor
tensor = torch.rand(3)
tensor + 10

tensor([10.9303, 10.9470, 10.3848])

In [11]:
# Multiply a tensor by 10
tensor * 10

tensor([9.3033, 9.4696, 3.8479])

In [ ]:
# Matrix Multiplication
# two main ways of performing multiplication in neural networks and deep learning :
# 1. Element wise multiplication
# 2. Matrix multiplication